










































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































services:
  - type: web
    name: Buddy-XTR
    env: node
    plan: free
    repo: https://github.com/carl24tech/Cyberion-Spark-X
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false  # Don't include the value here, will be entered manually on Render
      - key: OWNER_NUMBER
        sync: false
